### ISSUE TITLE
Text

### ISSUE THREAD

**Issue by colt05** [peeinears/MagicEye.js#12]
Add text support! Most Magic Eye generators on the internet allow text input, and since this is the best one, why not add text support?

**Comment by peeinears** [comment]
Hey @colt05, are you seeking support in the library or just in the hosted demo generator?

... Because text support already exists in the code! It's just not featured in the demo at http://peeinears.github.io/MagicEye.js/. The [TextDepthMapper](https://github.com/peeinears/MagicEye.js/blob/master/depthmappers/TextDepthMapper.js) takes a piece of text and then centers it, sizes it to fit, and generates a depth map that you can use to render a Magic Eye.

Check out [this example](https://github.com/peeinears/MagicEye.js/blob/master/examples/text.html).

**Comment by colt05** [comment]
Oh cool. Yeah, I meant the hosted demo generator.

**Comment by peeinears** [comment]
@colt05, I just put a text demo together. Check it out here: http://peeinears.github.io/MagicEye.js/text-to-magiceye.html

**Comment by colt05** [comment]
thanks!!!
